import type { RedPiece } from "./types";

/*
 * Historias de `docs/SOCIAL-KIT.md` §3 (H01…H10): secuencias de 3 a 5
 * pantallas verticales. Los stickers (link, encuesta, pregunta) se agregan en
 * Instagram al publicar; la placa les deja lugar abajo.
 */

const IG: RedPiece["channels"] = ["instagram"];
const STORY: RedPiece["formats"] = ["story"];

export const HISTORIAS: RedPiece[] = [
  {
    id: "H01",
    kind: "historias",
    name: "Lanzamiento",
    formats: STORY,
    channels: IG,
    days: [1],
    hook: "Hoy abrimos Ecommy.",
    cta: "Sticker de link a ecommy.app",
    hashtags: [],
    slides: [
      { template: "historia", title: "Hoy abrimos Ecommy." },
      { template: "historia", title: "Tiendas online para comercios que cobran por transferencia o WhatsApp." },
      { template: "captura", title: "Una tienda funcionando.", body: "demo.ecommy.app", placeholder: "Pegá acá la captura de la tienda demo" },
      { template: "historia", title: "Sin comisión por venta.", body: "14 días de Pro, sin tarjeta.", sticker: "link" },
    ],
  },
  {
    id: "H02",
    kind: "historias",
    name: "Cómo funciona en 4 pasos",
    formats: STORY,
    channels: IG,
    days: [],
    hook: "Creás la tienda y elegís el rubro.",
    cta: "Sticker de link a ecommy.app",
    hashtags: [],
    slides: [
      { template: "historia", kicker: "Cómo funciona · 1 de 4", title: "Creás la tienda y elegís el rubro." },
      { template: "historia", kicker: "Cómo funciona · 2 de 4", title: "Cargás o importás productos." },
      { template: "historia", kicker: "Cómo funciona · 3 de 4", title: "Compartís el link." },
      { template: "historia", kicker: "Cómo funciona · 4 de 4", title: "El pedido te llega armado.", cta: "Link en la bio" },
    ],
  },
  {
    id: "H03",
    kind: "historias",
    name: "Antes y después",
    formats: STORY,
    channels: IG,
    days: [],
    hook: "Menos preguntas, más ventas.",
    cta: "Sticker de link a la demo",
    hashtags: [],
    check: "El chat de “antes” lo armás vos, sin datos reales de clientes.",
    slides: [
      { template: "captura", kicker: "Antes", title: "“¿Precio?” “¿Talle?”", placeholder: "Pegá acá la captura del chat armado por vos" },
      { template: "captura", kicker: "Después", title: "El mismo pedido, armado desde la tienda.", placeholder: "Pegá acá la captura del pedido en WhatsApp" },
      { template: "historia", title: "Menos preguntas, más ventas.", sticker: "link" },
    ],
  },
  {
    id: "H04",
    kind: "historias",
    name: "Encuesta de precios",
    formats: STORY,
    channels: IG,
    days: [4],
    hook: "¿Cada cuánto actualizás precios?",
    cta: "Encuesta: Semanal / Mensual / Cuando me acuerdo",
    hashtags: [],
    check: "La segunda pantalla va al día siguiente, con el resultado real de la encuesta y el reel P05.",
    fields: [{ key: "resultado", token: "[resultado]", label: "Resultado de la encuesta", example: "La mitad, todas las semanas" }],
    slides: [
      { template: "historia", kicker: "Encuesta", title: "¿Cada cuánto actualizás precios?", sticker: "encuesta" },
      { template: "historia", kicker: "Lo que respondieron", title: "[resultado]", body: "Así se actualizan en masa, con Deshacer: mirá el reel en el perfil." },
    ],
  },
  {
    id: "H05",
    kind: "historias",
    name: "Pregunta de rubro",
    formats: STORY,
    channels: IG,
    days: [],
    hook: "¿Qué vendés? Te digo qué estilo de tienda te queda.",
    cta: "Sticker de pregunta",
    hashtags: [],
    check: "Mostrá el nombre de quien respondió sólo con su permiso.",
    fields: [
      { key: "rubro", token: "[rubro]", label: "Rubro de la respuesta", example: "Vinoteca" },
      { key: "estilo", token: "[estilo]", label: "Estilo que le recomendás", example: "Bodega" },
    ],
    slides: [
      { template: "historia", title: "¿Qué vendés?", body: "Te digo qué estilo de tienda te queda.", sticker: "pregunta" },
      { template: "captura", kicker: "Para [rubro]", title: "[estilo]", placeholder: "Pegá acá la captura del estilo" },
    ],
  },
  {
    id: "H06",
    kind: "historias",
    name: "Qué te frena",
    formats: STORY,
    channels: IG,
    days: [10],
    hook: "¿Qué te frena para tener tu tienda online?",
    cta: "Sticker de pregunta",
    hashtags: [],
    check: "Respondé con la respuesta de §7 del kit que corresponda a la objeción.",
    fields: [
      { key: "objecion", token: "[objeción]", label: "Objeción que te mandaron", example: "¿Cobran comisión?" },
      { key: "respuesta", token: "[respuesta]", label: "Respuesta (§7 del kit)", example: "No. La plata va directo a vos." },
    ],
    slides: [
      { template: "historia", title: "¿Qué te frena para tener tu tienda online?", sticker: "pregunta" },
      { template: "historia", kicker: "Me preguntaron", title: "[objeción]", body: "[respuesta]" },
    ],
  },
  {
    id: "H07",
    kind: "historias",
    name: "Checkout por transferencia",
    formats: STORY,
    channels: IG,
    days: [],
    hook: "Monto y datos bancarios en la página del pedido.",
    cta: "Sticker de link a la demo",
    hashtags: [],
    slides: [
      { template: "captura", title: "Monto y datos bancarios en la página del pedido.", placeholder: "Pegá acá la captura de la página del pedido" },
      { template: "captura", title: "Un toque en Copiar.", placeholder: "Pegá acá la captura del botón Copiar" },
      { template: "historia", title: "Enviar comprobante por WhatsApp.", body: "Probalo en demo.ecommy.app", sticker: "link" },
    ],
  },
  {
    id: "H08",
    kind: "historias",
    name: "Detrás de escena de la beta",
    formats: STORY,
    channels: IG,
    days: [16],
    hook: "Un comercio beta nos pidió [pedido].",
    cta: "Sticker de pregunta",
    hashtags: [],
    check: "Nombrá al comercio sólo con su permiso.",
    fields: [{ key: "pedido", token: "[pedido]", label: "Qué pidió el comercio", example: "imprimir remitos" }],
    slides: [
      { template: "historia", kicker: "Detrás de escena", title: "Un comercio beta nos pidió [pedido]." },
      { template: "captura", title: "La mejora, hecha.", placeholder: "Pegá acá la captura de la mejora" },
      { template: "historia", title: "Salió hoy." },
    ],
  },
  {
    id: "H09",
    kind: "historias",
    name: "Checklist de primeros pasos",
    formats: STORY,
    channels: IG,
    days: [24],
    hook: "Se tilda solo a medida que dejás lista la tienda.",
    cta: "Encuesta: ¿en qué paso estás?",
    hashtags: [],
    slides: [
      { template: "captura", kicker: "Primeros pasos", title: "El checklist del panel.", placeholder: "Pegá acá la captura del checklist del panel" },
      { template: "historia", title: "Se tilda solo a medida que dejás lista la tienda." },
      { template: "historia", title: "¿En qué paso estás?", sticker: "encuesta" },
    ],
  },
  {
    id: "H10",
    kind: "historias",
    name: "Qué viene",
    formats: STORY,
    channels: IG,
    days: [30],
    hook: "Lo próximo en Ecommy:",
    cta: "Sticker de pregunta",
    hashtags: [],
    check: "Sólo funciones confirmadas y en desarrollo (por ejemplo, cobro de planes con Mercado Pago).",
    fields: [{ key: "funcion", token: "[función]", label: "Función confirmada", example: "Cobro de planes con Mercado Pago" }],
    slides: [
      { template: "historia", title: "Lo próximo en Ecommy:" },
      { template: "historia", kicker: "En desarrollo", title: "[función]" },
      { template: "historia", title: "¿Qué te gustaría que agreguemos?", sticker: "pregunta" },
    ],
  },
];
