import {
  BadgeCheck,
  BadgePercent,
  Banknote,
  Box,
  Calendar,
  CircleHelp,
  Clock,
  CreditCard,
  Gift,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  House,
  Landmark,
  Leaf,
  Lock,
  MapPin,
  MessageCircle,
  Package,
  PackageCheck,
  Phone,
  Recycle,
  RefreshCcw,
  Ruler,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Tag,
  ThumbsUp,
  Timer,
  Truck,
  Undo2,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Íconos disponibles para el bloque `features` (nombre lucide → componente).
 * Lista curada de datos operativos (envíos, pagos, garantía, atención).
 * La comparten el render público y el selector del builder.
 */
export const FEATURE_ICONS: Partial<Record<string, LucideIcon>> = {
  Truck,
  Package,
  PackageCheck,
  Box,
  Store,
  MapPin,
  House,
  Landmark,
  Banknote,
  Wallet,
  CreditCard,
  BadgePercent,
  Tag,
  Gift,
  ShieldCheck,
  BadgeCheck,
  Lock,
  RefreshCcw,
  Undo2,
  Clock,
  Timer,
  Calendar,
  MessageCircle,
  Phone,
  Headphones,
  Handshake,
  Users,
  ThumbsUp,
  Heart,
  Star,
  Sparkles,
  Leaf,
  Recycle,
  Wrench,
  Hammer,
  Ruler,
  Scissors,
  ShoppingBag,
  Zap,
  CircleHelp,
};

export const FEATURE_ICON_LABELS: Record<string, string> = {
  Truck: "Envío",
  Package: "Paquete",
  PackageCheck: "Paquete listo",
  Box: "Caja",
  Store: "Local",
  MapPin: "Ubicación",
  House: "Casa",
  Landmark: "Banco / transferencia",
  Banknote: "Efectivo",
  Wallet: "Billetera",
  CreditCard: "Tarjeta",
  BadgePercent: "Descuento",
  Tag: "Etiqueta",
  Gift: "Regalo",
  ShieldCheck: "Garantía",
  BadgeCheck: "Verificado",
  Lock: "Compra segura",
  RefreshCcw: "Cambios",
  Undo2: "Devolución",
  Clock: "Horario",
  Timer: "Rapidez",
  Calendar: "Fecha",
  MessageCircle: "WhatsApp / chat",
  Phone: "Teléfono",
  Headphones: "Atención",
  Handshake: "Acuerdo",
  Users: "Equipo",
  ThumbsUp: "Recomendado",
  Heart: "Favorito",
  Star: "Destacado",
  Sparkles: "Novedad",
  Leaf: "Natural",
  Recycle: "Reciclable",
  Wrench: "Service",
  Hammer: "Herramienta",
  Ruler: "Medidas",
  Scissors: "A medida",
  ShoppingBag: "Compra",
  Zap: "Energía",
  CircleHelp: "Ayuda",
};
